$(document).ready(function(){
	$('.nav a').on('click',function(){
		$('.nav a').removeClass('active');
		$(this).addClass('active')
	});
	$('.project').hover(function(){
		$('#thumbnail1').css('opacity',0.2);
		$('#overflow-btn').css('opacity',1);
	},
	function(){
		$('#thumbnail1').css('opacity',1);
		$('#overflow-btn').css('opacity',0);
});
		$('.project2').hover(function(){
		$('#thumbnail2').css('opacity',0.2);
		$('#overflow-btn2').css('opacity',1);
	},
	function(){
		$('#thumbnail2').css('opacity',1);
		$('#overflow-btn2').css('opacity',0);
});
		$('.project3').hover(function(){
		$('#thumbnail3').css('opacity',0.2);
		$('#overflow-btn3').css('opacity',1);
	},
	function(){
		$('#thumbnail3').css('opacity',1);
		$('#overflow-btn3').css('opacity',0);
});
	});
